### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Joe-Development** [TheWolfBadger/DiscordTagIDs#4]
Hey!, id like to talk to you about your recent scripts "MenuTagID" my buddy's before you had it taken down off your repos said the code looked super similar to how i coded it and i was just wondering and getting in contact with you to clear this up hopefully you read this if you can add me up on discord and we'll talk there "discord:  joev2_dev" @JaredScar

**Comment by JaredScar** [comment]
No code has been taken from you. I do not need to copy other people's code. This is also not a valid issue. Closing.
